### ISSUE TITLE
Uncaught TypeError: au.shift is not a function

### ISSUE THREAD

**Issue by Laborouge** [discre-to/discreto#19]
Bonjour,
Et merci pour discre.to. C'est vraiment un outil simple et qui me facilite grandement la vie.

J'essaie d'implanter matomo avec discreto mais j'ai l'erreur suivante dans la console JS :
```
Uncaught TypeError: au.shift is not a function
    at aj (piwik.js:12:463)
    at ah (piwik.js:67:105)
    at Object.addTracker (piwik.js:69:112)
    at piwik.js:72:327
    at piwik.js:72:889
```
Pourriez-vous m'aider à y voir plus clair sur cette erreur s'il vous plait ?

Merci d'avance

**Comment by gregdeback** [comment]
Bonjour Laborouge,
Et merci pour votre intérêt pour le projet !
Je viens d'identifier le problème au niveau du service, et dès mon retour de congés je m'occuperai de pousser une mise à jour. Il s'agit de la commande "start" du service matomo :
```
start: (tracks) => {
  tracks.forEach((track) => w._paq.push(track))
},
```
doit être corrigé en :
```
start: (tracks) => {
  tracks.forEach((track) => w._paq.push([ track ]))
},
```

Je n'avais pas eu le souci avant, il est possible que ce soit lié à une mise à jour de Piwik/Matomo. Par ailleurs cela sera l'occasion de supporter la version "Cloud" de Matomo, actuellement il faut ruser un peu...

Merci de votre patience !
Greg

**Comment by Laborouge** [comment]
Merci beaucoup.
Je confirme que la correction à résolu le problème.

Encore merci pour Discreto. Longue vie au projet.
Mickaël
