### ISSUE TITLE
lazy load script dont work

### ISSUE THREAD

**Issue by Enigma-20** [discre-to/discreto#2]
I am trying to load an image with lazy loading true picture tag but because the discreto script is loaded first, lazy loading script is not applyed, how can I do please?

**Comment by gregdeback** [comment]
I'm not sure to understand what you mean, you just need to define the URL of the image in your config. Can you provide an excerpt of your conf? Or mail me directly: hello@discre.to

**Comment by Enigma-20** [comment]
i was able to do that, It was my mistake thank you for your reply
