### ISSUE TITLE
define other cookie as default

### ISSUE THREAD

**Issue by Enigma-20** [discre-to/discreto#3]
I am trying to load other cookie as default beside Cookie cookie consent, but just one of them is loaded, how can i do please?

**Comment by gregdeback** [comment]
Do you mean you're trying to use more than one cookie consent tool??

**Comment by Enigma-20** [comment]
no i al trying to define a another cookies but without let the user the choice to disable them, a security cookie and a session cookie.

**Comment by gregdeback** [comment]
That should not be a problem, as discreto only set/update one cookie, named after your preferences (by default "discreto"). As long as you're not using the same name, you should be able to define as many cookies you want, using `document.cookie = newCookie`.

**Comment by Enigma-20** [comment]
I am not trying to create a new one, the 2 cookies are already created, but i wana add them to the config. So the user see them in the popup 
Like that : 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/8KfG1sC/cookies0.png" alt="cookies0" border="0" /></a>

**Comment by gregdeback** [comment]
I got it, and yes, that is a good feature request: allow other cookies to be set as default (thus mandatory). Issues reopened, and labelled "Enhancement".

**Comment by gregdeback** [comment]
Now you can add a mandatory cookie:
```
"_mandatory":{
  "name": "Required cookie",
  "about": "We need that",
  "types": [ "mandatory" ],
  "force": true
}
```
