### ISSUE TITLE
Cookie expiration date is wrong

### ISSUE THREAD

**Issue by Enigma-20** [discre-to/discreto#4]
When I use discreto.min.js on your my server and not from yours, the expiration date is wrong. when i specify 365 days the expiration date is ../../2051 , 31 years.
I think you can add parseInt() to y.cookie.days

**Comment by gregdeback** [comment]
You're right, I was able to reproduce the problem, days *must be* an int, not a string :
days: '365' => problem
days: 365 => ok
I'll add parseInt() as you suggest in the next commit.
